.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. braindecode

.. _braindecode: https://braindecode.org
.. _braindecode-github: https://github.com/braindecode/braindecode
.. _braindecode-pypi: https://pypi.org/project/braindecode
.. _braindecode-contribution-guide: https://github.com/braindecode/braindecode/blob/master/CONTRIBUTING.md
.. _braindecode-chat: https://gitter.im/braindecodechat/community
.. _braindecode-issues: https://github.com/braindecode/braindecode/issues/
.. _braindecode-pulls: https://github.com/braindecode/braindecode/pulls/

.. mne

.. _MNE-Python: http://mne.tools/
.. _MNE-glossary-data-channels: https://mne.tools/stable/documentation/glossary.html#term-data-channels
.. _MNE-clinical-60-sleep: https://mne.tools/stable/auto_tutorials/clinical/60_sleep.html

.. moabb

.. _MOABB: https://moabb.neurotechx.com
.. _MOABB-github: https://github.com/NeuroTechX/moabb

.. main dependencies

.. _PyTorch: https://pytorch.org
.. _skorch: https://skorch.readthedocs.io/en/stable
.. _torchvision: https://pytorch.org/vision/stable/index.html
.. _lightning: https://lightning.ai/pytorch-lightning
.. _numpy: http://www.numpy.org
.. _scipy: http://www.scipy.org
.. _h5py: http://www.h5py.org
.. _pytest: https://docs.pytest.org/
.. _Flake8: http://flake8.pycqa.org/
.. _coverage: https://pypi.python.org/pypi/coverage
.. _joblib: https://pypi.python.org/pypi/joblib
.. _scikit-learn: https://scikit-learn.org/stable/
.. _matplotlib: https://matplotlib.org/
.. _sphinx: https://www.sphinx-doc.org/
.. _pandas: https://pandas.pydata.org/
.. _tqdm: https://tqdm.github.io/
.. _pooch: https://www.fatiando.org/pooch/latest/

.. git stuff

.. _git: https://git-scm.com/
.. _github: https://github.com

.. other stuff

.. _python: http://www.python.org
.. _Brain Imaging Data Structure: https://bids.neuroimaging.io/
.. _Sphinx documentation: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
.. _sphinx-gallery: https://sphinx-gallery.github.io
.. _NumPy docstring style guidelines: https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard

.. vim: ft=rst
