on: [status]
jobs:
  circleci_artifacts_redirector:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLECI_TOKEN }}
          artifact-path: 0/dev/index.html
          circleci-jobs: fetch_docs_from_github
          job-title: Check rendered doc here!
